apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  namespace: monitoring
spec:
  ingress:
    enabled: true
  deployment:
    skipCreateAdminAccount: false
  config:
    log:
      mode: "console"
